### ISSUE TITLE
Transfer to JuliaText?

### ISSUE THREAD

**Issue by aviks** [sadit/SnowballStemmer.jl#6]
Hi @sadit 

I was planning to separate out the the stemmer functionality from TextAnalysis, and register a separate package. I did not realise that your package existed, and started work here:  https://github.com/JuliaText/Snowball.jl. The idea is for TextAnalysis.jl to use that as a dependency. 

The main advantage of my version is that uses a prebuilt libraries using binary builder (which allows this to be used on windows easily), and I've added some documenter docs. 

So there are a few options to achieve this

1. I could do a PR with my changes on top of this

2. You could move this repo to JuliaText, and I can merge my changes on top. (you'll maintain access of course)

3. With your permission, I rename my repo to SnowballStemmer.jl and register a new version from there (and add you as collaborater to the repo) 

I'd like at 2) to happen before taking a dependency on TextAnalysis. 3) is easier, and should be OK for your dependencies since most of the code is originally from TextAnalysis.jl anyways.  

Let me know what you think. I hope you don't mind me reaching out to you do discuss this.

**Comment by sadit** [comment]
Hi @aviks 

Thanks for asking. The third option sounds good for me. Please let me know if I can help you with the process.

**Comment by aviks** [comment]
I have actually registered https://github.com/JuliaText/Snowball.jl. @sadit you should have an invite for access. This repo can be deprecated if you want.
